### PR TITLE
Add support for the D7000

### PR DESCRIPTION
**Pull request by Tanganelli**
I noticed that the D7000 requires the headers set according to my modification. It should be fine even for the others models.

### CODE REVIEW

**Comment by MatMaul** [comment]
Thanks, can you try to minimize it through trial and error? My guess is that Accept, content encoding and Content type are enough.

**Comment by MatMaul** [comment]
And soapaction of course 😉

**Comment by Tanganelli** [comment]
I'll try tomorrow and let you know, but maybe you are right. I think that also the Host could be removed.

**Comment by MatMaul** [comment]
Up ?

**Comment by MatMaul** [comment]
@Tanganelli little up :)

**Comment by Tanganelli** [comment]
Hi sorry, I was really busy I'll try to come back to you ASAP.

Il giorno mar 2 ott 2018 alle ore 08:38 Mathieu Velten <
notifications@github.com> ha scritto:

**Comment by MatMaul** [comment]
Should be fixed by #49

**Pull request closed without merging**
