### PR TITLE
enable/disable Guest Wifi

### PR DESCRIPTION
**Pull request by moranbf**
I copied some conde for enable_config and disable_config, but wrote code to disable and enable guest wifi. Where set_guest_wifi_enable(SSID,SSID_KEY) is probably limited to 16 characters at this point, but could be expanded to 63, I looks like they key is broken into 4 xml tags <key1><key2>..4. But I only coded for one.

### CODE REVIEW

**Comment by moranbf** [comment]
merge to master?

**Comment by MatMaul** [comment]
Can you squash those commits in one with the same message as this PR title, and remove .idea/vcs.xml ? Thanks.

**Comment by moranbf** [comment]
Will do, might be a few days

**Comment by MatMaul** [comment]
And please rebase and try to follow the pattern introduced in my refactor for the requests ;)

**Comment by MatMaul** [comment]
And complete the README with the new public methods please.

**Comment by MatMaul** [comment]
I just added a `params` parameter to `_make_request` to make your life easier :)
55cdd822749153dd9bbb3a2fa0340914acbdddac

**Comment by starkillerOG** [comment]
I will close this PR since the new PR: https://github.com/MatMaul/pynetgear/pull/120 includes these features using the folowing functions:
```
netgear.set_2g_guest_access_enabled(True)
netgear.set_5g_guest_access_enabled(True)
netgear.get_2g_guest_access_enabled()
netgear.get_5g_guest_access_enabled()
```

**Pull request closed without merging**
